### ISSUE TITLE
Eye-Able's request for removal

### ISSUE THREAD

**Issue by karlgroves** [karlgroves/overlayfactsheet#1086]
I received the following email from the Co-founder and CTO of Eye-Able yesterday and am sharing his email, with his permission. This email is shared verbatim with no changes.

---------- Original Message ----------
Dear Mr. Groves,

I am the head of development at Eye-Able. We are a young German startup
focused on developing solutions that help users access information on
the Internet.

We recently saw that our software is listed on [overlayfactsheet.com](http://overlayfactsheet.com/). I
would like to emphasize that we do not perform any automatic repairs and
do not aim at WCAG compliance in any way. We completely agree that this
should not and cannot be done automatically at this time.

Our assistive software was developed in collaboration with the German
Institute for the Blind to provide easily accessible visual features
(such as contrast, font size, or reading aloud) for users who don't use
other assistive technologies. You can try our browser extension here:

https://chrome.google.com/webstore/detail/eye-able%C2%AE-accessibility-a/mpifhmmgeeofnfpehedbokjmlcgnlhbn?hl=de

While we are technically an overlay that adds functions to an existing
website, our goal is not to provide compliance, but to provide
additional visual customization, unlike other competitors listed on your
site.

We also offer WCAG testing solutions that highlight potential errors on
websites similar to Axe or Wave. But that is completely separate.

We hope to convince you that our software is different and should not be
listed on the overlay factsheet (or least not as an automatic compliance
software). We'd also be happy to discuss this in a face-to-face meeting
or any other suitable format.

Thank you very much for your time!

Best wishes from Germany

Tobias Greiner

--
Tobias Greiner
Co-Founder and CTO
[www.eye-able.com](http://www.eye-able.com/)

Web Inclusion GmbH
Gartenstraße 12c
97276 Margetshöchheim
Amtsgericht Würzburg | HRB 15330
USt.-Id Nr. DE 337341524
Geschäftsführer: Oliver Greiner

**Comment by tcaspers** [comment]
How would a blind or vision-impaired person, who deliberately chose to ignore “contrast, font size, or reading aloud” features of the operating system and “who don't use other assistive technologies” be able to find and access a website which uses eye-able and then, and only then switch on the presumably needed “contrast, font size, or reading aloud” features on that particular website?

**Comment by karlgroves** [comment]
I'd like to give @Tobias-Eye-Able some kudos for the polite and informative email.  There's definitely a lot to be said for his message's tone and its *extreme* divergence from the tone of messages I've received from other overlay vendors.

Here are my comments relating to the above:

A cursory review of the Eye-Able website shows that they clearly do sell an overlay widget with the same common features as the rest.  On that basis alone, it should remain included.  

Tobias's claims, above, that they "do not aim at WCAG compliance in any way. " is true.  When I went through their website, they didn't make any false claims.

However, Eye-Able is still subject to the [same criticism](https://overlayfactsheet.com/#strengths-and-weaknesses-of-overlay-widgets)s that the Overlay Factsheet makes against widgets.   In addition, I have [privacy concerns](https://overlayfactsheet.com/#privacy), though Eye-Able appears to be [doing the right things](https://eye-able.com/en/datenschutzerklaerung-assist/) with respect to GDPR.

While I'm encouraged by Tobias's statements above, the product is clearly an overlay.  That said, I want more comments from the community on this.

**Comment by aardrian** [comment]
I agree that with a cursory glance it does not make the same false claims as others do around WCAG conformance. There is certainly a false _implication_ given some easily identifiable WCAG violations within the overlay controls, which means its use on a site will introduce WCAG violations.

A generalized accessibility tool should not introduce more problems (or risk) than it is meant to solve.

I think it is fine to keep it on the list.

**Comment by TobiasG95** [comment]
Thank you for taking the time to review our case. We are very open to discussing this issue and understand the controversy surrounding it, especially with AI-based solutions that promise full compliance.

We are very open to discussion and believe that our assistance software can add value for certain user groups when implemented on websites. Would you also consider solutions like the one on the American Council of the Blind (top right in the navigation at https://www.acb.org/) to be useless to users? These features, such as contrast adjustment and font size adjustment, are basically the same as in Eye-Able Assist, except that they are not grouped in an overlay menu.

Regarding @tcaspers' question, the software is not intended to help people who already use other assistive technologies, especially screen readers. Before developing the software, we studied the issue in a university context together with German institutes for the visually impaired. The main feedback was that many people who can still see quite well (above about 30% vision) often don't know about operating system functionalities and are often not technically inclined enough to access them, e.g. elderly people. "Overlays" that provide visual customization options on frequently used web pages can provide easy access and benefit to these users. We get a lot of very positive feedback from our users, which encourages us that our software is helping. In addition to the website plugin (which is manually customized for each of our clients' domains), we also offer a browser extension for people who want to use it on any website.

@aardrian  The accessibility of our own software is also a primary concern of our development. Every major update is tested by an external WCAG certification institute. What WCAG violations have you found in Eye-Able Assist during your testing? I'd be happy to take a look at them and fix them in the next update!

Thanks @karlgroves for taking the time to test us again. You also mentioned GDPR, which is an important topic especially in Germany. We also offer local hosting integrations and encourage all our customers to implement them. Apart from that, we only use EU servers and don't collect any personal data and especially don't track users.

It would be important for us not to be in the same pot as other vendors who promise full compliance without any human intervention. We don't think the technology is ready for that and won't be for some time (if ever). To achieve compliance, we believe a mix of automated domain-wide testing, combined with human audits and workshops, is the ideal way to go. Assistive software like Eye-Able Assist can be a benefit for some, but of course not for everyone. 

Would you consider at least splitting your list into solutions that promise full AI compliance and solutions that add visual assistance? These two groups have very different approaches and goals. Being in the same list can be very misleading, I hope you understand that.

I am happy to answer any other questions or concerns you may have! 

Best wishes from Germany
Tobias

**Comment by aardrian** [comment]
> Would you also consider solutions like the one on the American Council of the Blind (top right in the navigation at https://www.acb.org/) to be useless to users?

It is demonstrably useless to keyboard users, so yes.

> @aardrian The accessibility of our own software is also a primary concern of our development. Every major update is tested by an external WCAG certification institute. What WCAG violations have you found in Eye-Able Assist during your testing? I'd be happy to take a look at them and fix them in the next update!

I don't do free testing. However, as a _very_ quick example, when I put my cursor over the overlay trigger and the "tool-tip" appears, tell me how that does not fail the _Dismissible_ or _Hoverable_ clauses of 1.4.13.

Also, what is a "WCAG certification institute"? I don't see a VPAT/ACR with the results of a WCAG test on the tool itself. I see no references to a certification for the product. Either way, I think you should ask them to re-test the entire application with an updated contract that asks for guarantees if they give you a full WCAG pass.

> Would you consider at least splitting your list into solutions that promise full AI compliance and solutions that focus on adding visual assistance?

Most of the overlay vendors listed who claim any AI intervention have been doing it falsely for years. Their claims of WCAG conformance are, IMO, far bigger issues than any hand-wavy AI references.

**Comment by TobiasG95** [comment]
> I don't do free testing. However, as a _very_ quick example, when I put my cursor over the overlay trigger and the "tool-tip" appears, tell me how that does not fail the _Dismissible_ or _Hoverable_ clauses of 1.4.13.

Thanks for your feedback and of course I completly understand! At first glance you are right, the current design does not meet the "hoverable" criterion (https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html). Since there is no clickable content in the tooltip, I dismissed it so far, but I agree that this should be improved. 

> Also, what is a "WCAG certification institute"? I don't see a VPAT/ACR with the results of a WCAG test on the tool itself. I see no references to a certification for the product. Either way, I think you should ask them to re-test the entire application with an updated contract that asks for guarantees if they give you a full WCAG pass.

By certification institute, I mean German institutions that are recognized as independent testing bodies for the BITV (the German derivate of the WCAG). This is the latest test result (unfortunately only in German), but I will also contact them with your feedback: https://webinclusioneyeable.sharepoint.com/:b:/s/WebInclusionGmbH/EedLJdYixrhOqBZNEexEUvkB21ztAjNLAIbgm20AGiDbww?e=TJoaO2

> Most of the overlay vendors listed who claim any AI intervention have been doing it falsely for years. Their claims of WCAG conformance are, IMO, far bigger issues than any hand-wavy AI references.

I completly agree! That's we we want to distance ourselfes from others that offer these false claims.

**Comment by aardrian** [comment]
> At first glance you are right, the current design does not meet the "hoverable" criterion (https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html). Since there is no clickable content in the tooltip, I dismissed it so far, but I agree that this should be improved.

Nor _Dismissable_.

> By certification institute, I mean German institutions that are recognized as independent testing bodies for the BITV (the German derivate of the WCAG). This is the latest test result (unfortunately only in German), but I will also contact them with your feedback: [https://webinclusioneyeable.sharepoint.com/🅱️/s/WebInclusionGmbH/EedLJdYixrhOqBZNEexEUvkB21ztAjNLAIbgm20AGiDbww?e=TJoaO2](https://webinclusioneyeable.sharepoint.com/:b:/s/WebInclusionGmbH/EedLJdYixrhOqBZNEexEUvkB21ztAjNLAIbgm20AGiDbww?e=TJoaO2)

I feel you should link this from the site (prominently) to demonstrate you went through that effort and a third party has given it whatever marks it gave it.

Also, the BITV testers marked [9.1.4.13](https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/9-1-4-13-eingeblendete-inhalte-bedienbar) (the WCAG SC 1.4.3 analogue) as "not applicable". I find that confounding considering it is almost literally the first thing I noticed about the overlay trigger and seemingly _every control_ within the overlay itself. Heck, BITV's own tester called out the "tool-tips" in the 2.1.1 test, so it's not like their presence was a surprise:

> Einschränkung: nicht alle im Browser Chrome nutzbaren TastaturKurzbefehle sind im Browser Firefox nutzbar. Entsprechend erscheinen diese in Firefox dann nicht in den Tooltipps.

Anyway, I stand by my initial feedback.

**Comment by dnikub** [comment]
The overlay fact sheet lists facts about overlays. EyeAble is a widget with features similar to other widget/overlay companies and is also integrated with a line of code. So for me, this is an overlay which qualifies it for being listed. 

I like that you, @TobiasG95 acknowledge in your email that only automated solutions are insufficient. You also clearly state that you do not sell WCAG compliance, so I think your wish to split up the list of overlay vendors makes sense. The listed overlays all classify as overlay, but they do have different (marketing) claims and promises. 

I can also see that your widget features could be helpful for some people if they know what such a widget is, what it can do and where on the website it is located to turn it on. But redundancy is something to discuss, so the ["Strengths and weaknesses of overlay widgets"](https://overlayfactsheet.com/#strengths-and-weaknesses-of-overlay-widgets) section does apply to you, which is an argument for being listed. The other sections probably don't apply to EyeAble, which argues for a splitted list of overlay companies.

In addition, I have some other things to critique on EyeAble.

1. I feel like, in general, the main focus should be on creating an accessible website. If the basis is set and a website is accessible, such software could be added "on top" to assist people that might need it (elderly, people without much knowledge of IT, etc.). That a website should be accessible first is not clearly communicated on your website.
2. When quickly looking at your website, some improvements could be made (font sizes, heading structure, contrast, animations, etc.). For example, I need to use the widget to increase the font size because it is way too small in some cases in the first place. Or when I click the "stop animation" button that _"stops moving elements and animations on the page"_, there is still movement (animated numbers counting up, FAQ toggle). Movement is also still there if I reduce motion in my system settings. You promote your package/services for accessibility and digital inclusion. Shouldn't someone promoting digital inclusion software make their own website inclusive/accessible?

So my impression is that EyeAble (a) is an overlay, that (b) doesn't promise compliance, but (c) also doesn't put the focus on accessible web experiences for every individual in the first place.

**Comment by TobiasG95** [comment]
> Anyway, I stand by my initial feedback.

I agree and we will fix this in the next update. I will also reach out to our tester to see why this was skipped in the previous audit.

> I like that you, @TobiasG95 acknowledge in your email that only automated solutions are insufficient. You also clearly state that you do not sell WCAG compliance, so I think your wish to split up the list of overlay vendors makes sense. The listed overlays all classify as overlay, but they do have different (marketing) claims and promises.

@dnikub Thanks for your open feedback! Splitting the list would be much appreciated. We also believe that our software should be placed on top of an already accessible website. I apologize that our website didn't reflect this correctly. We are a small team and have been focusing on our products and neglecting our own website. We are currently in the process of a complete redesign of the website, which will address all the current accessibility issues that we are very much aware of (which, of course, does not justify them...)

**Comment by colabottles** [comment]
> While we are technically an overlay that adds functions to an existing
> website, our goal is not to provide compliance, but to provide
> additional visual customization, unlike other competitors listed on your
> site.

That is all I needed to read to make a decision about whether they should be taken off the list. No. They shouldn’t. I am in total agreement with the comments that have been given as feedback so far. 

I appreciate the candor and openness, but the fact remains that it is an overlay by the very definition of the word.

**Comment by brothercake** [comment]
I accept that this organization is operating in good faith, and not engaging in deceptive marketing, but they are providing an overlay tool that gives bad-faith clients the ability to ignore accessibility requirements. 

It should remain on the list.

**Comment by TobiasG95** [comment]
Hi everyone,
I wanted to follow up on the idea of whether it's possible to split the list into two groups, one that promises automatic (often AI-based) fixes with the goal of achieving automatic WCAG compliance, and another that offers visual customization options without making automatic fixes for code-based issues. I understand much of the criticism, but from the user feedback we get on a daily basis, there is still a big target audience, especially for example people with 20-70% vision or elderly people, who benefit from on-site visual features because they don't know about OS features or aren't "disabled enough" to use them.

I agree with everyone that automatic fixes like some vendors advertise don't work, but that approach is very different from Eye-Able Assist. A common use case is for exmpale our browser extension that works on any website.

Also, would it be possible to change the name on the list from Eye-Able.com to Eye-Able Assist? As I mentioned, the core software solution of Eye-Able is actually a WCAG audit tool to automatically find problems on websites (where possible). This should not be included in the overlay list. (More info about the audit here: https://eye-able.com/en/audit/)

Thanks for your time and open discussion!

**Comment by karlgroves** [comment]
I just want to add a comment here, for completeness, that Eye-able have allegedly been engaging in some of the single most shady marketing of any overlay company on the market.

It has always been my personal view that the biggest problem with overlays isn't that they can't make things accessible, but rather that they engage in deceptive marketing. What Eye-Able appears to be doing now, wit respect to sending out deceptive, forged emails, would make them the worst of the worst in terms of shady marketing.

https://www.linkedin.com/posts/karlgroves_new-alleged-shadiness-from-an-overlay-vendor-activity-7279165282701520896-bxwk?utm_source=share&utm_medium=member_desktop

**Comment by TobiasG95** [comment]
Hi Karl,
thanks for sharing this and I am devastated that you received such an email. Eye-Able is 100% not sending out forged emails and engaging in such activities.

If you would be willing to share details of this contact on my personal email, I will start an investigation on this matter and update you on the results.

Thank you for you help and we will find out what is happening asap.

**Comment by karlgroves** [comment]
Given that the email was sent to me in confidence, I'm not willing to share any more details.

**Comment by TobiasG95** [comment]
Thank you for your quicky reply and bringing this to my and Eye-Able's attention.

I completely understand. I will find out what I can with the information you shared. We will get to the bottom if this is an misunderstanding or someone missusing Eye-Able's name.
